/**
 * Skill Code Generator
 *
 * Generates TypeScript skill modules from MCP tool definitions.
 * Each generated skill includes:
 * - Input type from JSON Schema
 * - Async function decorated with skill metadata
 * - Error handling and result types
 * - SKILL.md documentation with YAML frontmatter
 * - LICENSE.txt file
 * - README.md for the skills collection
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ToolDefinition, ServerTools, GeneratorOptions } from "../types.js";
import {
  generateInterface,
  toPascalCase,
  toCamelCase,
  toValidIdentifier,
} from "./schema-to-ts.js";
import { logger } from "../utils/logger.js";

/**
 * Generated file content
 */
interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Generate skill files for all servers
 */
export async function generateSkills(
  servers: ServerTools[],
  options: GeneratorOptions
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  // Filter servers if specified
  const filteredServers = options.serverFilter
    ? servers.filter((s) => s.serverName === options.serverFilter)
    : servers;

  if (filteredServers.length === 0) {
    throw new Error(
      options.serverFilter
        ? `Server "${options.serverFilter}" not found`
        : "No servers to process"
    );
  }

  // Generate runtime file first
  if (options.inlineRuntime) {
    files.push({
      path: join(options.outputDir, "runtime.ts"),
      content: generateRuntimeModule(),
    });
  }

  // Generate skills for each server
  for (const server of filteredServers) {
    const serverFiles = await generateServerSkills(server, options);
    files.push(...serverFiles);
  }

  // Generate index file
  files.push({
    path: join(options.outputDir, "index.ts"),
    content: generateIndexFile(filteredServers, options),
  });

  // Generate LICENSE.txt
  files.push({
    path: join(options.outputDir, "LICENSE.txt"),
    content: generateLicenseFile(),
  });

  // Generate README.md
  files.push({
    path: join(options.outputDir, "README.md"),
    content: generateReadmeFile(filteredServers),
  });

  // Write files unless in preview mode
  if (!options.preview) {
    await writeGeneratedFiles(files);
  }

  return files;
}

/**
 * Generate skills for a single server
 */
async function generateServerSkills(
  server: ServerTools,
  options: GeneratorOptions
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];
  const serverDir = join(options.outputDir, toValidIdentifier(server.serverName));

  // Filter tools if specified
  const tools = options.toolFilter
    ? server.tools.filter((t) => options.toolFilter!.includes(t.name))
    : server.tools;

  // Generate SKILL.md for the server
  files.push({
    path: join(serverDir, "SKILL.md"),
    content: generateServerSkillMd(server.serverName, tools),
  });

  // Generate each skill file
  for (const tool of tools) {
    const skillContent = generateSkillFile(tool, server.serverName, options);
    files.push({
      path: join(serverDir, `${toValidIdentifier(tool.name)}.ts`),
      content: skillContent,
    });
  }

  // Generate server index
  files.push({
    path: join(serverDir, "index.ts"),
    content: generateServerIndex(tools, server.serverName),
  });

  return files;
}

/**
 * Generate a single skill file
 */
function generateSkillFile(
  tool: ToolDefinition,
  serverName: string,
  options: GeneratorOptions
): string {
  const funcName = toCamelCase(tool.name);
  const inputTypeName = `${toPascalCase(tool.name)}Input`;
  const resultTypeName = `${toPascalCase(tool.name)}Result`;

  const lines: string[] = [];

  // File header with enhanced documentation
  lines.push(`/**`);
  lines.push(` * @fileoverview ${tool.name} skill for ${serverName}`);
  lines.push(` * @module ${serverName}/${tool.name}`);
  lines.push(` *`);
  lines.push(` * Skill: ${tool.name}`);
  lines.push(` * Server: ${serverName}`);
  if (tool.description) {
    lines.push(` *`);
    // Format multi-line descriptions properly
    const descLines = tool.description.split('\n');
    for (const line of descLines) {
      lines.push(` * ${line}`);
    }
  }
  lines.push(` *`);
  lines.push(` * @example`);
  lines.push(` * \`\`\`typescript`);
  lines.push(` * import { ${funcName} } from "./${toValidIdentifier(tool.name)}.js";`);
  lines.push(` * import { RuntimeAuthManager } from "../runtime.js";`);
  lines.push(` *`);
  lines.push(` * const authManager = new RuntimeAuthManager();`);
  lines.push(` * const context = authManager.getOrCreateSession("user-id", "${serverName}");`);
  lines.push(` *`);
  lines.push(` * const result = await ${funcName}({ /* params */ }, context);`);
  lines.push(` * if (result.success) {`);
  lines.push(` *   console.log(result.data);`);
  lines.push(` * }`);
  lines.push(` * \`\`\``);
  lines.push(` *`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` * @see {@link ${serverName}/SKILL.md} for full documentation`);
  lines.push(` */`);
  lines.push(``);

  // Imports
  if (options.inlineRuntime) {
    lines.push(`import { skill, type SkillContext, type SkillResult } from "../runtime.js";`);
  } else {
    lines.push(`import { skill, type SkillContext, type SkillResult } from "mcp2skills/runtime";`);
  }
  lines.push(``);

  // Generate input type with enhanced documentation
  const inputInterface = generateInterface(
    inputTypeName,
    tool.inputSchema as Parameters<typeof generateInterface>[1],
    `Input parameters for ${tool.name}`
  );
  lines.push(inputInterface);
  lines.push(``);

  // Generate result type with enhanced documentation
  lines.push(`/**`);
  lines.push(` * Result from ${tool.name}`);
  lines.push(` *`);
  lines.push(` * @property success - Whether the skill executed successfully`);
  lines.push(` * @property data - The result data if successful`);
  lines.push(` * @property error - Error message if unsuccessful`);
  lines.push(` */`);
  lines.push(`export type ${resultTypeName} = SkillResult<unknown>;`);
  lines.push(``);

  // Generate the skill function with enhanced JSDoc
  lines.push(`/**`);
  if (tool.description) {
    const descLines = tool.description.split('\n');
    for (const line of descLines) {
      lines.push(` * ${line}`);
    }
    lines.push(` *`);
  }
  lines.push(` * @param input - The input parameters (see {@link ${inputTypeName}})`);
  lines.push(` * @param context - Skill execution context with auth and MCP client`);
  lines.push(` * @returns Promise resolving to the skill result`);
  lines.push(` * @throws Will not throw; errors are captured in the result object`);
  lines.push(` */`);
  lines.push(`export const ${funcName} = skill({`);
  lines.push(`  name: "${tool.name}",`);
  lines.push(`  server: "${serverName}",`);
  if (tool.description) {
    lines.push(`  description: ${JSON.stringify(tool.description)},`);
  }
  lines.push(`}, async (`);
  lines.push(`  input: ${inputTypeName},`);
  lines.push(`  context: SkillContext`);
  lines.push(`): Promise<${resultTypeName}> => {`);
  lines.push(`  return context.callTool("${tool.name}", input as Record<string, unknown>);`);
  lines.push(`});`);
  lines.push(``);

  // Export the skill metadata with documentation
  lines.push(`// ============================================================================`);
  lines.push(`// Skill Metadata`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  lines.push(`/** @readonly The unique name of this skill */`);
  lines.push(`${funcName}.skillName = "${tool.name}";`);
  lines.push(``);
  lines.push(`/** @readonly The server this skill belongs to */`);
  lines.push(`${funcName}.serverName = "${serverName}";`);
  if (tool.description) {
    lines.push(``);
    lines.push(`/** @readonly Description of what this skill does */`);
    lines.push(`${funcName}.description = ${JSON.stringify(tool.description)};`);
  }
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate server index file
 */
function generateServerIndex(tools: ToolDefinition[], serverName: string): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * @fileoverview ${serverName} Skills Index`);
  lines.push(` * @module ${serverName}`);
  lines.push(` *`);
  lines.push(` * This module exports all skills for the ${serverName} MCP server.`);
  lines.push(` *`);
  lines.push(` * ## Available Skills`);
  lines.push(` *`);
  for (const tool of tools) {
    const shortDesc = tool.description?.split('\n')[0]?.substring(0, 60) || 'No description';
    lines.push(` * - {@link ${toCamelCase(tool.name)}} - ${shortDesc}${shortDesc.length >= 60 ? '...' : ''}`);
  }
  lines.push(` *`);
  lines.push(` * @example`);
  lines.push(` * \`\`\`typescript`);
  lines.push(` * import { ${tools.slice(0, 2).map(t => toCamelCase(t.name)).join(', ')} } from "./${toValidIdentifier(serverName)}/index.js";`);
  lines.push(` * \`\`\``);
  lines.push(` *`);
  lines.push(` * @see {@link ./SKILL.md} for detailed documentation`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` */`);
  lines.push(``);

  // Export all skills with grouping
  lines.push(`// ============================================================================`);
  lines.push(`// Skill Exports`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  for (const tool of tools) {
    const moduleName = toValidIdentifier(tool.name);
    const funcName = toCamelCase(tool.name);
    lines.push(`export { ${funcName} } from "./${moduleName}.js";`);
    lines.push(`export type { ${toPascalCase(tool.name)}Input } from "./${moduleName}.js";`);
  }
  lines.push(``);

  // Export skill list with better documentation
  lines.push(`// ============================================================================`);
  lines.push(`// Skill Registry`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * All skill names for ${serverName}`);
  lines.push(` * @readonly`);
  lines.push(` */`);
  lines.push(`export const skillNames = [`);
  for (const tool of tools) {
    lines.push(`  "${tool.name}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);
  lines.push(`/** Type representing any skill name in this server */`);
  lines.push(`export type SkillName = typeof skillNames[number];`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate main index file
 */
function generateIndexFile(servers: ServerTools[], options: GeneratorOptions): string {
  const lines: string[] = [];
  const totalSkills = servers.reduce((sum, s) => sum + s.tools.length, 0);

  lines.push(`/**`);
  lines.push(` * @fileoverview Generated MCP Skills`);
  lines.push(` * @module generated_skills`);
  lines.push(` *`);
  lines.push(` * Auto-generated skill modules from MCP servers.`);
  lines.push(` *`);
  lines.push(` * ## Summary`);
  lines.push(` * - **${servers.length}** server(s)`);
  lines.push(` * - **${totalSkills}** skill(s) total`);
  lines.push(` *`);
  lines.push(` * ## Servers`);
  for (const server of servers) {
    lines.push(` * - {@link ${toValidIdentifier(server.serverName)}} - ${server.tools.length} skill(s)`);
  }
  lines.push(` *`);
  lines.push(` * @example`);
  lines.push(` * \`\`\`typescript`);
  lines.push(` * import { RuntimeAuthManager, ${toValidIdentifier(servers[0]?.serverName || 'MyServer')} } from "./index.js";`);
  lines.push(` *`);
  lines.push(` * const authManager = new RuntimeAuthManager();`);
  lines.push(` * const context = authManager.getOrCreateSession("user", "server");`);
  lines.push(` * const result = await ${toValidIdentifier(servers[0]?.serverName || 'MyServer')}.someSkill(params, context);`);
  lines.push(` * \`\`\``);
  lines.push(` *`);
  lines.push(` * @see {@link ./README.md} for full documentation`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` */`);
  lines.push(``);

  // Export runtime
  lines.push(`// ============================================================================`);
  lines.push(`// Runtime Exports`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  if (options.inlineRuntime) {
    lines.push(`export * from "./runtime.js";`);
  } else {
    lines.push(`export * from "mcp2skills/runtime";`);
  }
  lines.push(``);

  // Export each server namespace
  lines.push(`// ============================================================================`);
  lines.push(`// Server Skill Modules`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  for (const server of servers) {
    const serverModule = toValidIdentifier(server.serverName);
    lines.push(`/** ${server.serverName} skills (${server.tools.length} skills) */`);
    lines.push(`export * as ${serverModule} from "./${serverModule}/index.js";`);
    lines.push(``);
  }

  // Export server list
  lines.push(`// ============================================================================`);
  lines.push(`// Server Registry`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * All configured MCP servers`);
  lines.push(` * @readonly`);
  lines.push(` */`);
  lines.push(`export const servers = [`);
  for (const server of servers) {
    lines.push(`  "${server.serverName}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);
  lines.push(`/** Type representing any server name */`);
  lines.push(`export type ServerName = typeof servers[number];`);
  lines.push(``);

  // Export skill registry
  lines.push(`// ============================================================================`);
  lines.push(`// Skill Registry`);
  lines.push(`// ============================================================================`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Registry of all skills organized by server`);
  lines.push(` *`);
  lines.push(` * @example`);
  lines.push(` * \`\`\`typescript`);
  lines.push(` * import { skillRegistry } from "./index.js";`);
  lines.push(` *`);
  lines.push(` * for (const [server, skills] of Object.entries(skillRegistry)) {`);
  lines.push(` *   console.log(\`\${server}: \${skills.length} skills\`);`);
  lines.push(` * }`);
  lines.push(` * \`\`\``);
  lines.push(` * @readonly`);
  lines.push(` */`);
  lines.push(`export const skillRegistry = {`);
  for (const server of servers) {
    lines.push(`  "${server.serverName}": [`);
    for (const tool of server.tools) {
      lines.push(`    "${tool.name}",`);
    }
    lines.push(`  ],`);
  }
  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`/** Type representing any skill name across all servers */`);
  lines.push(`export type AnySkillName = typeof skillRegistry[ServerName][number];`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate the runtime module
 */
function generateRuntimeModule(): string {
  return `/**
 * Runtime support for generated skills
 * 
 * Provides:
 * - Skill decorator
 * - Auth management
 * - MCP client pooling
 * - Multi-session support
 * 
 * @generated by mcp2skills
 */

// ============================================================================
// Types
// ============================================================================

/**
 * Result of a skill execution
 */
export interface SkillResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  isError?: boolean;
}

/**
 * Skill execution context
 */
export interface SkillContext {
  /** Session/user identifier */
  sessionId: string;
  /** Server this skill belongs to */
  serverName: string;
  /** Call an MCP tool */
  callTool(name: string, params: Record<string, unknown>): Promise<SkillResult>;
  /** Get authentication headers */
  getAuthHeaders(): Promise<Record<string, string>>;
}

/**
 * Skill metadata
 */
export interface SkillMetadata {
  name: string;
  server: string;
  description?: string;
}

/**
 * Skill function type
 */
export type SkillFunction<TInput = unknown, TOutput = unknown> = ((
  input: TInput,
  context: SkillContext
) => Promise<SkillResult<TOutput>>) & {
  skillName: string;
  serverName: string;
  description?: string;
};

// ============================================================================
// Skill Decorator
// ============================================================================

/**
 * Create a skill function with metadata
 */
export function skill<TInput, TOutput>(
  metadata: SkillMetadata,
  fn: (input: TInput, context: SkillContext) => Promise<SkillResult<TOutput>>
): SkillFunction<TInput, TOutput> {
  const skillFn = fn as SkillFunction<TInput, TOutput>;
  skillFn.skillName = metadata.name;
  skillFn.serverName = metadata.server;
  skillFn.description = metadata.description;
  return skillFn;
}

// ============================================================================
// Auth Credentials
// ============================================================================

export type AuthType = "none" | "api_key" | "bearer" | "oauth";

export interface AuthCredentials {
  authType: AuthType;
  accessToken?: string;
  apiKey?: string;
  apiKeyHeader?: string;
  refreshToken?: string;
  expiresAt?: Date;
}

// ============================================================================
// Server Configuration
// ============================================================================

export interface MCPServerConfig {
  name: string;
  transport: "stdio" | "sse" | "http";
  command?: string;
  args?: string[];
  url?: string;
  authType?: AuthType;
  authConfig?: Record<string, unknown>;
}

// ============================================================================
// Session Context
// ============================================================================

/**
 * Session-specific skill context
 */
class SessionContext implements SkillContext {
  constructor(
    public sessionId: string,
    public serverName: string,
    private authManager: RuntimeAuthManager
  ) {}

  async callTool(name: string, params: Record<string, unknown>): Promise<SkillResult> {
    return this.authManager.executeToolCall(this.sessionId, this.serverName, name, params);
  }

  async getAuthHeaders(): Promise<Record<string, string>> {
    return this.authManager.getAuthHeaders(this.sessionId, this.serverName);
  }
}

// ============================================================================
// Runtime Auth Manager
// ============================================================================

/**
 * Manages authentication and MCP connections for multi-user chatbot scenarios
 */
export class RuntimeAuthManager {
  private serverConfigs: Map<string, MCPServerConfig> = new Map();
  private sessionCredentials: Map<string, Map<string, AuthCredentials>> = new Map();
  private connections: Map<string, unknown> = new Map(); // Server connections

  /**
   * Add a server configuration
   */
  addServerConfig(config: MCPServerConfig): void {
    this.serverConfigs.set(config.name, config);
  }

  /**
   * Get or create a session context for a user
   */
  getOrCreateSession(sessionId: string, serverName: string): SkillContext {
    // Ensure session exists
    if (!this.sessionCredentials.has(sessionId)) {
      this.sessionCredentials.set(sessionId, new Map());
    }
    return new SessionContext(sessionId, serverName, this);
  }

  /**
   * Authenticate a session for a specific server
   */
  async authenticateSession(
    sessionId: string,
    serverName: string,
    credentials: AuthCredentials
  ): Promise<void> {
    if (!this.sessionCredentials.has(sessionId)) {
      this.sessionCredentials.set(sessionId, new Map());
    }
    this.sessionCredentials.get(sessionId)!.set(serverName, credentials);
  }

  /**
   * Get authentication headers for a session/server
   */
  async getAuthHeaders(sessionId: string, serverName: string): Promise<Record<string, string>> {
    const sessionCreds = this.sessionCredentials.get(sessionId);
    const credentials = sessionCreds?.get(serverName);

    if (!credentials || credentials.authType === "none") {
      return {};
    }

    switch (credentials.authType) {
      case "bearer":
        if (credentials.accessToken) {
          return { Authorization: \`Bearer \${credentials.accessToken}\` };
        }
        break;
      case "api_key":
        if (credentials.apiKey) {
          const header = credentials.apiKeyHeader || "X-API-Key";
          return { [header]: credentials.apiKey };
        }
        break;
      case "oauth":
        if (credentials.accessToken) {
          // Check expiration
          if (credentials.expiresAt && new Date() >= credentials.expiresAt) {
            throw new Error("OAuth token expired. Please re-authenticate.");
          }
          return { Authorization: \`Bearer \${credentials.accessToken}\` };
        }
        break;
    }

    return {};
  }

  /**
   * Execute a tool call for a session
   */
  async executeToolCall(
    sessionId: string,
    serverName: string,
    toolName: string,
    params: Record<string, unknown>
  ): Promise<SkillResult> {
    // This is a placeholder - in real implementation, this would:
    // 1. Get or create MCP client connection for the server
    // 2. Apply session authentication
    // 3. Execute the tool call
    // 4. Return the result

    // For now, throw an error indicating the runtime needs to be configured
    throw new Error(
      \`Runtime not fully configured. To execute skills, you need to:\\n\` +
      \`1. Create a RuntimeAuthManager instance\\n\` +
      \`2. Add server configs with addServerConfig()\\n\` +
      \`3. Authenticate sessions with authenticateSession()\\n\` +
      \`4. Use getOrCreateSession() to get a context\\n\\n\` +
      \`Attempted: \${serverName}/\${toolName}\`
    );
  }

  /**
   * Execute a skill for a session
   */
  async executeSkill<TInput, TOutput>(
    sessionId: string,
    skill: SkillFunction<TInput, TOutput>,
    input: TInput
  ): Promise<SkillResult<TOutput>> {
    const context = this.getOrCreateSession(sessionId, skill.serverName);
    return skill(input, context);
  }

  /**
   * Close a session and cleanup resources
   */
  async closeSession(sessionId: string): Promise<void> {
    this.sessionCredentials.delete(sessionId);
  }

  /**
   * Close all sessions and connections
   */
  async shutdown(): Promise<void> {
    this.sessionCredentials.clear();
    this.connections.clear();
  }
}

// ============================================================================
// Exports
// ============================================================================

/** Default runtime auth manager instance */
export const defaultAuthManager = new RuntimeAuthManager();

/**
 * Helper to list all available skills
 */
export function listSkills(registry: Record<string, readonly string[]>): string[] {
  const skills: string[] = [];
  for (const [server, serverSkills] of Object.entries(registry)) {
    for (const skill of serverSkills) {
      skills.push(\`\${server}/\${skill}\`);
    }
  }
  return skills;
}
`;
}

/**
 * Generate SKILL.md file for a server
 */
function generateServerSkillMd(serverName: string, tools: ToolDefinition[]): string {
  const toolList = tools.map(t => `- \`${t.name}\`: ${t.description || 'No description'}`).join('\n');
  const toolNames = tools.map(t => t.name).join(', ');
  
  return `---
name: ${serverName.toLowerCase()}
description: Generated MCP skills for ${serverName}. Provides ${tools.length} skill(s) for interacting with the ${serverName} MCP server. Use these skills when you need to: ${toolNames}.
license: Complete terms in LICENSE.txt
---

# ${serverName} Skills

Auto-generated TypeScript skills from the ${serverName} MCP server.

## Overview

This skill module provides typed wrappers for ${tools.length} MCP tool(s) from the ${serverName} server.
Each skill is a self-contained async function that can be executed with proper authentication context.

## Available Skills

${toolList}

## Usage

\`\`\`typescript
import { RuntimeAuthManager } from "../runtime.js";
import { ${tools.slice(0, 3).map(t => toCamelCase(t.name)).join(', ')}${tools.length > 3 ? ', ...' : ''} } from "./index.js";

// Create auth manager and configure server
const authManager = new RuntimeAuthManager();
authManager.addServerConfig({
  name: "${serverName}",
  transport: "http", // or "stdio", "sse"
  url: "https://your-mcp-server.com/mcp"
});

// Get session context
const context = authManager.getOrCreateSession("user-123", "${serverName}");

// Execute skills
const result = await ${toCamelCase(tools[0]?.name || 'mySkill')}({ /* params */ }, context);

if (result.success) {
  console.log("Result:", result.data);
} else {
  console.error("Error:", result.error);
}
\`\`\`

## Skill Details

${tools.map(t => `### ${t.name}

${t.description || 'No description available.'}

**Function:** \`${toCamelCase(t.name)}\`
`).join('\n')}

## Authentication

Skills require a \`SkillContext\` which is obtained from the \`RuntimeAuthManager\`.
The context handles authentication automatically based on the server configuration.

Supported auth types:
- \`none\` - No authentication
- \`api_key\` - API key in header
- \`bearer\` - Bearer token
- \`oauth\` - OAuth 2.0 client credentials

## Generated by

This skill module was auto-generated by [mcp2skills](https://github.com/your-org/mcp2skills).
`;
}

/**
 * Generate LICENSE.txt file (Apache 2.0)
 */
function generateLicenseFile(): string {
  const year = new Date().getFullYear();
  return `
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright ${year} Generated by mcp2skills

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
`;
}

/**
 * Generate README.md file for the generated skills directory
 */
function generateReadmeFile(servers: ServerTools[]): string {
  const totalSkills = servers.reduce((sum, s) => sum + s.tools.length, 0);
  const serverList = servers.map(s => 
    `- **${s.serverName}**: ${s.tools.length} skill(s) - See [${s.serverName}/SKILL.md](./${toValidIdentifier(s.serverName)}/SKILL.md)`
  ).join('\n');
  
  return `# Generated MCP Skills

Auto-generated TypeScript skill modules from MCP (Model Context Protocol) servers.

## Overview

This directory contains **${totalSkills} skills** from **${servers.length} server(s)**:

${serverList}

## Quick Start

### 1. Import Skills

\`\`\`typescript
import { RuntimeAuthManager } from "./runtime.js";
import * as ${toValidIdentifier(servers[0]?.serverName || 'MyServer')} from "./${toValidIdentifier(servers[0]?.serverName || 'MyServer')}/index.js";
\`\`\`

### 2. Configure Authentication

\`\`\`typescript
const authManager = new RuntimeAuthManager();

// Add server configuration
authManager.addServerConfig({
  name: "${servers[0]?.serverName || 'my-server'}",
  transport: "http",
  url: "https://your-mcp-server.com/mcp",
  authType: "bearer"
});

// Authenticate user session
await authManager.authenticateSession("user-123", "${servers[0]?.serverName || 'my-server'}", {
  authType: "bearer",
  accessToken: "user-token-here"
});
\`\`\`

### 3. Execute Skills

\`\`\`typescript
// Get session context
const context = authManager.getOrCreateSession("user-123", "${servers[0]?.serverName || 'my-server'}");

// Execute a skill
const result = await ${toValidIdentifier(servers[0]?.serverName || 'MyServer')}.${toCamelCase(servers[0]?.tools[0]?.name || 'mySkill')}({
  // skill parameters
}, context);

if (result.success) {
  console.log("Success:", result.data);
} else {
  console.error("Error:", result.error);
}
\`\`\`

### 4. Cleanup

\`\`\`typescript
// Close user session
await authManager.closeSession("user-123");

// Shutdown all connections
await authManager.shutdown();
\`\`\`

## File Structure

\`\`\`
generated_skills/
├── README.md           # This file
├── LICENSE.txt         # Apache 2.0 License
├── index.ts            # Main exports and skill registry
├── runtime.ts          # Authentication and execution runtime
${servers.map(s => `└── ${toValidIdentifier(s.serverName)}/
    ├── SKILL.md        # Skill documentation with YAML frontmatter
    ├── index.ts        # Server-specific exports
${s.tools.slice(0, 3).map(t => `    ├── ${toValidIdentifier(t.name)}.ts`).join('\n')}${s.tools.length > 3 ? `\n    └── ... (${s.tools.length - 3} more)` : ''}`).join('\n')}
\`\`\`

## Skill Registry

All skills are registered in \`index.ts\`:

\`\`\`typescript
import { skillRegistry, servers } from "./index.js";

// List all servers
console.log(servers); // ${JSON.stringify(servers.map(s => s.serverName))}

// List skills by server
for (const [server, skills] of Object.entries(skillRegistry)) {
  console.log(\`\${server}: \${skills.length} skills\`);
}
\`\`\`

## Authentication Types

| Type | Description | Config |
|------|-------------|--------|
| \`none\` | No authentication | - |
| \`api_key\` | API key in header | \`apiKey\`, \`apiKeyHeader\` |
| \`bearer\` | Bearer token | \`accessToken\` |
| \`oauth\` | OAuth 2.0 | \`accessToken\`, \`refreshToken\`, \`expiresAt\` |

## Multi-User Support

The \`RuntimeAuthManager\` supports multi-user scenarios for chatbots:

\`\`\`typescript
// Each user gets their own session
const user1Context = authManager.getOrCreateSession("user-1", "server");
const user2Context = authManager.getOrCreateSession("user-2", "server");

// Authenticate each user independently
await authManager.authenticateSession("user-1", "server", {
  authType: "bearer",
  accessToken: "user-1-token"
});

// Execute skills with user-specific context
const result = await someSkill(params, user1Context);
\`\`\`

## License

These generated skills are provided under the Apache 2.0 License. See [LICENSE.txt](./LICENSE.txt).

## Generated By

This module was auto-generated by [mcp2skills](https://github.com/your-org/mcp2skills).

Generated at: ${new Date().toISOString()}
`;
}

/**
 * Write generated files to disk
 */
async function writeGeneratedFiles(files: GeneratedFile[]): Promise<void> {
  // Collect unique directories
  const dirs = new Set<string>();
  for (const file of files) {
    const dir = file.path.substring(0, file.path.lastIndexOf("/"));
    dirs.add(dir);
  }

  // Create directories
  for (const dir of dirs) {
    await mkdir(dir, { recursive: true });
  }

  // Write files
  for (const file of files) {
    await writeFile(file.path, file.content, "utf-8");
    logger.debug(`Written: ${file.path}`);
  }
}

/**
 * Preview generated files without writing
 */
export function previewSkills(files: GeneratedFile[]): void {
  for (const file of files) {
    logger.info(logger.bold(`\n=== ${file.path} ===\n`));
    logger.info(file.content);
  }
}
