/**
 * Skill Code Generator
 *
 * Generates TypeScript skill modules from MCP tool definitions.
 * Each generated skill includes:
 * - Input type from JSON Schema
 * - Async function decorated with skill metadata
 * - Error handling and result types
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ToolDefinition, ServerTools, GeneratorOptions } from "../types.js";
import {
  generateInterface,
  toPascalCase,
  toCamelCase,
  toValidIdentifier,
} from "./schema-to-ts.js";
import { logger } from "../utils/logger.js";

/**
 * Generated file content
 */
interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Generate skill files for all servers
 */
export async function generateSkills(
  servers: ServerTools[],
  options: GeneratorOptions
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];

  // Filter servers if specified
  const filteredServers = options.serverFilter
    ? servers.filter((s) => s.serverName === options.serverFilter)
    : servers;

  if (filteredServers.length === 0) {
    throw new Error(
      options.serverFilter
        ? `Server "${options.serverFilter}" not found`
        : "No servers to process"
    );
  }

  // Generate runtime file first
  if (options.inlineRuntime) {
    files.push({
      path: join(options.outputDir, "runtime.ts"),
      content: generateRuntimeModule(),
    });
  }

  // Generate skills for each server
  for (const server of filteredServers) {
    const serverFiles = await generateServerSkills(server, options);
    files.push(...serverFiles);
  }

  // Generate index file
  files.push({
    path: join(options.outputDir, "index.ts"),
    content: generateIndexFile(filteredServers, options),
  });

  // Write files unless in preview mode
  if (!options.preview) {
    await writeGeneratedFiles(files);
  }

  return files;
}

/**
 * Generate skills for a single server
 */
async function generateServerSkills(
  server: ServerTools,
  options: GeneratorOptions
): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];
  const serverDir = join(options.outputDir, toValidIdentifier(server.serverName));

  // Filter tools if specified
  const tools = options.toolFilter
    ? server.tools.filter((t) => options.toolFilter!.includes(t.name))
    : server.tools;

  // Generate each skill file
  for (const tool of tools) {
    const skillContent = generateSkillFile(tool, server.serverName, options);
    files.push({
      path: join(serverDir, `${toValidIdentifier(tool.name)}.ts`),
      content: skillContent,
    });
  }

  // Generate server index
  files.push({
    path: join(serverDir, "index.ts"),
    content: generateServerIndex(tools, server.serverName),
  });

  return files;
}

/**
 * Generate a single skill file
 */
function generateSkillFile(
  tool: ToolDefinition,
  serverName: string,
  options: GeneratorOptions
): string {
  const funcName = toCamelCase(tool.name);
  const inputTypeName = `${toPascalCase(tool.name)}Input`;
  const resultTypeName = `${toPascalCase(tool.name)}Result`;

  const lines: string[] = [];

  // File header
  lines.push(`/**`);
  lines.push(` * Skill: ${tool.name}`);
  lines.push(` * Server: ${serverName}`);
  if (tool.description) {
    lines.push(` *`);
    lines.push(` * ${tool.description}`);
  }
  lines.push(` *`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` */`);
  lines.push(``);

  // Imports
  if (options.inlineRuntime) {
    lines.push(`import { skill, type SkillContext, type SkillResult } from "../runtime.js";`);
  } else {
    lines.push(`import { skill, type SkillContext, type SkillResult } from "mcp2skills/runtime";`);
  }
  lines.push(``);

  // Generate input type
  const inputInterface = generateInterface(
    inputTypeName,
    tool.inputSchema as Parameters<typeof generateInterface>[1],
    `Input parameters for ${tool.name}`
  );
  lines.push(inputInterface);
  lines.push(``);

  // Generate result type
  lines.push(`/**`);
  lines.push(` * Result from ${tool.name}`);
  lines.push(` */`);
  lines.push(`export type ${resultTypeName} = SkillResult<unknown>;`);
  lines.push(``);

  // Generate the skill function
  lines.push(`/**`);
  if (tool.description) {
    lines.push(` * ${tool.description}`);
    lines.push(` *`);
  }
  lines.push(` * @param input - The input parameters`);
  lines.push(` * @param context - Skill execution context with auth and MCP client`);
  lines.push(` * @returns Promise resolving to the skill result`);
  lines.push(` */`);
  lines.push(`export const ${funcName} = skill({`);
  lines.push(`  name: "${tool.name}",`);
  lines.push(`  server: "${serverName}",`);
  if (tool.description) {
    lines.push(`  description: ${JSON.stringify(tool.description)},`);
  }
  lines.push(`}, async (`);
  lines.push(`  input: ${inputTypeName},`);
  lines.push(`  context: SkillContext`);
  lines.push(`): Promise<${resultTypeName}> => {`);
  lines.push(`  return context.callTool("${tool.name}", input as Record<string, unknown>);`);
  lines.push(`});`);
  lines.push(``);

  // Export the skill metadata
  lines.push(`// Skill metadata for discovery`);
  lines.push(`${funcName}.skillName = "${tool.name}";`);
  lines.push(`${funcName}.serverName = "${serverName}";`);
  if (tool.description) {
    lines.push(`${funcName}.description = ${JSON.stringify(tool.description)};`);
  }
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate server index file
 */
function generateServerIndex(tools: ToolDefinition[], serverName: string): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Skills for ${serverName}`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` */`);
  lines.push(``);

  // Export all skills
  for (const tool of tools) {
    const moduleName = toValidIdentifier(tool.name);
    const funcName = toCamelCase(tool.name);
    lines.push(`export { ${funcName} } from "./${moduleName}.js";`);
    lines.push(`export type { ${toPascalCase(tool.name)}Input } from "./${moduleName}.js";`);
  }
  lines.push(``);

  // Export skill list
  lines.push(`/** All skill names for ${serverName} */`);
  lines.push(`export const skillNames = [`);
  for (const tool of tools) {
    lines.push(`  "${tool.name}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate main index file
 */
function generateIndexFile(servers: ServerTools[], options: GeneratorOptions): string {
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Generated MCP Skills`);
  lines.push(` * @generated by mcp2skills`);
  lines.push(` */`);
  lines.push(``);

  // Export runtime
  if (options.inlineRuntime) {
    lines.push(`export * from "./runtime.js";`);
  } else {
    lines.push(`export * from "mcp2skills/runtime";`);
  }
  lines.push(``);

  // Export each server namespace
  for (const server of servers) {
    const serverModule = toValidIdentifier(server.serverName);
    lines.push(`// ${server.serverName} skills`);
    lines.push(`export * as ${serverModule} from "./${serverModule}/index.js";`);
  }
  lines.push(``);

  // Export server list
  lines.push(`/** All configured servers */`);
  lines.push(`export const servers = [`);
  for (const server of servers) {
    lines.push(`  "${server.serverName}",`);
  }
  lines.push(`] as const;`);
  lines.push(``);

  // Export skill registry
  lines.push(`/** Registry of all skills by server */`);
  lines.push(`export const skillRegistry = {`);
  for (const server of servers) {
    lines.push(`  "${server.serverName}": [`);
    for (const tool of server.tools) {
      lines.push(`    "${tool.name}",`);
    }
    lines.push(`  ],`);
  }
  lines.push(`} as const;`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Generate the runtime module
 */
function generateRuntimeModule(): string {
  return `/**
 * Runtime support for generated skills
 * 
 * Provides:
 * - Skill decorator
 * - Auth management
 * - MCP client pooling
 * - Multi-session support
 * 
 * @generated by mcp2skills
 */

// ============================================================================
// Types
// ============================================================================

/**
 * Result of a skill execution
 */
export interface SkillResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  isError?: boolean;
}

/**
 * Skill execution context
 */
export interface SkillContext {
  /** Session/user identifier */
  sessionId: string;
  /** Server this skill belongs to */
  serverName: string;
  /** Call an MCP tool */
  callTool(name: string, params: Record<string, unknown>): Promise<SkillResult>;
  /** Get authentication headers */
  getAuthHeaders(): Promise<Record<string, string>>;
}

/**
 * Skill metadata
 */
export interface SkillMetadata {
  name: string;
  server: string;
  description?: string;
}

/**
 * Skill function type
 */
export type SkillFunction<TInput = unknown, TOutput = unknown> = ((
  input: TInput,
  context: SkillContext
) => Promise<SkillResult<TOutput>>) & {
  skillName: string;
  serverName: string;
  description?: string;
};

// ============================================================================
// Skill Decorator
// ============================================================================

/**
 * Create a skill function with metadata
 */
export function skill<TInput, TOutput>(
  metadata: SkillMetadata,
  fn: (input: TInput, context: SkillContext) => Promise<SkillResult<TOutput>>
): SkillFunction<TInput, TOutput> {
  const skillFn = fn as SkillFunction<TInput, TOutput>;
  skillFn.skillName = metadata.name;
  skillFn.serverName = metadata.server;
  skillFn.description = metadata.description;
  return skillFn;
}

// ============================================================================
// Auth Credentials
// ============================================================================

export type AuthType = "none" | "api_key" | "bearer" | "oauth";

export interface AuthCredentials {
  authType: AuthType;
  accessToken?: string;
  apiKey?: string;
  apiKeyHeader?: string;
  refreshToken?: string;
  expiresAt?: Date;
}

// ============================================================================
// Server Configuration
// ============================================================================

export interface MCPServerConfig {
  name: string;
  transport: "stdio" | "sse" | "http";
  command?: string;
  args?: string[];
  url?: string;
  authType?: AuthType;
  authConfig?: Record<string, unknown>;
}

// ============================================================================
// Session Context
// ============================================================================

/**
 * Session-specific skill context
 */
class SessionContext implements SkillContext {
  constructor(
    public sessionId: string,
    public serverName: string,
    private authManager: RuntimeAuthManager
  ) {}

  async callTool(name: string, params: Record<string, unknown>): Promise<SkillResult> {
    return this.authManager.executeToolCall(this.sessionId, this.serverName, name, params);
  }

  async getAuthHeaders(): Promise<Record<string, string>> {
    return this.authManager.getAuthHeaders(this.sessionId, this.serverName);
  }
}

// ============================================================================
// Runtime Auth Manager
// ============================================================================

/**
 * Manages authentication and MCP connections for multi-user chatbot scenarios
 */
export class RuntimeAuthManager {
  private serverConfigs: Map<string, MCPServerConfig> = new Map();
  private sessionCredentials: Map<string, Map<string, AuthCredentials>> = new Map();
  private connections: Map<string, unknown> = new Map(); // Server connections

  /**
   * Add a server configuration
   */
  addServerConfig(config: MCPServerConfig): void {
    this.serverConfigs.set(config.name, config);
  }

  /**
   * Get or create a session context for a user
   */
  getOrCreateSession(sessionId: string, serverName: string): SkillContext {
    // Ensure session exists
    if (!this.sessionCredentials.has(sessionId)) {
      this.sessionCredentials.set(sessionId, new Map());
    }
    return new SessionContext(sessionId, serverName, this);
  }

  /**
   * Authenticate a session for a specific server
   */
  async authenticateSession(
    sessionId: string,
    serverName: string,
    credentials: AuthCredentials
  ): Promise<void> {
    if (!this.sessionCredentials.has(sessionId)) {
      this.sessionCredentials.set(sessionId, new Map());
    }
    this.sessionCredentials.get(sessionId)!.set(serverName, credentials);
  }

  /**
   * Get authentication headers for a session/server
   */
  async getAuthHeaders(sessionId: string, serverName: string): Promise<Record<string, string>> {
    const sessionCreds = this.sessionCredentials.get(sessionId);
    const credentials = sessionCreds?.get(serverName);

    if (!credentials || credentials.authType === "none") {
      return {};
    }

    switch (credentials.authType) {
      case "bearer":
        if (credentials.accessToken) {
          return { Authorization: \`Bearer \${credentials.accessToken}\` };
        }
        break;
      case "api_key":
        if (credentials.apiKey) {
          const header = credentials.apiKeyHeader || "X-API-Key";
          return { [header]: credentials.apiKey };
        }
        break;
      case "oauth":
        if (credentials.accessToken) {
          // Check expiration
          if (credentials.expiresAt && new Date() >= credentials.expiresAt) {
            throw new Error("OAuth token expired. Please re-authenticate.");
          }
          return { Authorization: \`Bearer \${credentials.accessToken}\` };
        }
        break;
    }

    return {};
  }

  /**
   * Execute a tool call for a session
   */
  async executeToolCall(
    sessionId: string,
    serverName: string,
    toolName: string,
    params: Record<string, unknown>
  ): Promise<SkillResult> {
    // This is a placeholder - in real implementation, this would:
    // 1. Get or create MCP client connection for the server
    // 2. Apply session authentication
    // 3. Execute the tool call
    // 4. Return the result

    // For now, throw an error indicating the runtime needs to be configured
    throw new Error(
      \`Runtime not fully configured. To execute skills, you need to:\\n\` +
      \`1. Create a RuntimeAuthManager instance\\n\` +
      \`2. Add server configs with addServerConfig()\\n\` +
      \`3. Authenticate sessions with authenticateSession()\\n\` +
      \`4. Use getOrCreateSession() to get a context\\n\\n\` +
      \`Attempted: \${serverName}/\${toolName}\`
    );
  }

  /**
   * Execute a skill for a session
   */
  async executeSkill<TInput, TOutput>(
    sessionId: string,
    skill: SkillFunction<TInput, TOutput>,
    input: TInput
  ): Promise<SkillResult<TOutput>> {
    const context = this.getOrCreateSession(sessionId, skill.serverName);
    return skill(input, context);
  }

  /**
   * Close a session and cleanup resources
   */
  async closeSession(sessionId: string): Promise<void> {
    this.sessionCredentials.delete(sessionId);
  }

  /**
   * Close all sessions and connections
   */
  async shutdown(): Promise<void> {
    this.sessionCredentials.clear();
    this.connections.clear();
  }
}

// ============================================================================
// Exports
// ============================================================================

/** Default runtime auth manager instance */
export const defaultAuthManager = new RuntimeAuthManager();

/**
 * Helper to list all available skills
 */
export function listSkills(registry: Record<string, readonly string[]>): string[] {
  const skills: string[] = [];
  for (const [server, serverSkills] of Object.entries(registry)) {
    for (const skill of serverSkills) {
      skills.push(\`\${server}/\${skill}\`);
    }
  }
  return skills;
}
`;
}

/**
 * Write generated files to disk
 */
async function writeGeneratedFiles(files: GeneratedFile[]): Promise<void> {
  // Collect unique directories
  const dirs = new Set<string>();
  for (const file of files) {
    const dir = file.path.substring(0, file.path.lastIndexOf("/"));
    dirs.add(dir);
  }

  // Create directories
  for (const dir of dirs) {
    await mkdir(dir, { recursive: true });
  }

  // Write files
  for (const file of files) {
    await writeFile(file.path, file.content, "utf-8");
    logger.debug(`Written: ${file.path}`);
  }
}

/**
 * Preview generated files without writing
 */
export function previewSkills(files: GeneratedFile[]): void {
  for (const file of files) {
    logger.info(logger.bold(`\n=== ${file.path} ===\n`));
    logger.info(file.content);
  }
}
